from __future__ must occur at the beginning
SyntaxError: from __future__ imports must occur at
the beginning of the file

(cherry picked from commit 468ac54acef2b363dbcadb687ab0186bc22fac15)